exports.seed = async function (knex) {
  await knex("students").del();
  await knex("students").insert([
    {
      full_name: "John Doe",
      age: 20,
      address_id: 1,
      univer_id: 1,
    },
    {
      full_name: "Jane Smith",
      age: 22,
      address_id: 2,
      univer_id: 2,
    },
    {
      full_name: "Aliyev Vali",
      age: 21,
      address_id: 3,
      univer_id: 3,
    },
    {
      full_name: "John Doe",
      age: 20,
      address_id: 1,
      univer_id: 1,
    },
    {
      full_name: "Jane Smith",
      age: 22,
      address_id: 2,
      univer_id: 2,
    },
    {
      full_name: "Aliyev Vali",
      age: 21,
      address_id: 3,
      univer_id: 3,
    },
    {
      full_name: "John Doe",
      age: 20,
      address_id: 1,
      univer_id: 1,
    },
    {
      full_name: "Jane Smith",
      age: 22,
      address_id: 2,
      univer_id: 2,
    },
    {
      full_name: "Aliyev Vali",
      age: 21,
      address_id: 3,
      univer_id: 3,
    },
    {
      full_name: "John Doe",
      age: 20,
      address_id: 1,
      univer_id: 1,
    },
    {
      full_name: "Jane Smith",
      age: 22,
      address_id: 2,
      univer_id: 2,
    },
    {
      full_name: "Aliyev Vali",
      age: 21,
      address_id: 3,
      univer_id: 3,
    },
    {
      full_name: "John Doe",
      age: 20,
      address_id: 1,
      univer_id: 1,
    },
    {
      full_name: "Jane Smith",
      age: 22,
      address_id: 2,
      univer_id: 2,
    },
    {
      full_name: "Aliyev Vali",
      age: 21,
      address_id: 3,
      univer_id: 3,
    },
    {
      full_name: "John Doe",
      age: 20,
      address_id: 1,
      univer_id: 1,
    },
    {
      full_name: "Jane Smith",
      age: 22,
      address_id: 2,
      univer_id: 2,
    },
    {
      full_name: "Aliyev Vali",
      age: 21,
      address_id: 3,
      univer_id: 3,
    },
    {
      full_name: "John Doe",
      age: 20,
      address_id: 1,
      univer_id: 1,
    },
    {
      full_name: "Jane Smith",
      age: 22,
      address_id: 2,
      univer_id: 2,
    },
    {
      full_name: "Aliyev Vali",
      age: 21,
      address_id: 3,
      univer_id: 3,
    },
    {
      full_name: "John Doe 3",
      age: 20,
      address_id: 1,
      univer_id: 1,
    },
    {
      full_name: "Jane Smith 1",
      age: 22,
      address_id: 2,
      univer_id: 2,
    },
    {
      full_name: "Aliyev Vali 4",
      age: 21,
      address_id: 3,
      univer_id: 3,
    },
    {
      full_name: "John Doe 1",
      age: 20,
      address_id: 1,
      univer_id: 1,
    },
    {
      full_name: "Jane Smith 2",
      age: 22,
      address_id: 2,
      univer_id: 2,
    },
    {
      full_name: "Aliyev Vali 3",
      age: 21,
      address_id: 3,
      univer_id: 3,
    },
    {
      full_name: "John Doe 3",
      age: 20,
      address_id: 1,
      univer_id: 1,
    },
    {
      full_name: "Jane Smith 1",
      age: 22,
      address_id: 2,
      univer_id: 2,
    },
    {
      full_name: "Aliyev Vali 2",
      age: 21,
      address_id: 1,
      univer_id: 3,
    },
  ]);
};
